"use client";

import { useMemo, useState } from "react";
import {
  Bell, CalendarDays, ChevronDown, CircleHelp, CloudRain, Download, Expand, Gauge,
  LocateFixed, Map as MapIcon, Minus, Navigation, Pause, Play, Plus, Search, Settings2,
  Share2, Waves, Wind, X,
} from "lucide-react";

import { ErrorState, MiniSparkline, Skeleton, StaticBasinMap } from "@/components";
import { useAssimilation, useDates, useForecast, useGrid, useTimeseries } from "@/lib/api";
import { forecastGridForSelectedCell, transformMap, type MapView } from "@/lib/transforms";

function formatIst(value: string | null | undefined) {
  if (!value) return "Unavailable";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(date) + " IST";
}

function formatDate(date: string) {
  const parsed = new Date(`${date.length === 10 ? date + "T00:00:00" : date}`);
  return Number.isNaN(parsed.getTime()) ? date : new Intl.DateTimeFormat("en-IN", { month: "short", day: "numeric", timeZone: "Asia/Kolkata" }).format(parsed);
}

function display(value: number | null | undefined, unit = "") {
  return value === null || value === undefined || !Number.isFinite(value) ? "Unavailable" : `${value.toFixed(1)}${unit ? ` ${unit}` : ""}`;
}

function Toggle({ enabled, onChange, label }: { enabled: boolean; onChange: () => void; label: string }) {
  return <button type="button" aria-label={`${label}: ${enabled ? "on" : "off"}`} aria-pressed={enabled} onClick={onChange} className={`relative h-[18px] w-8 shrink-0 rounded-pill transition-colors ${enabled ? "bg-primary" : "bg-slate-300"}`}><span className={`absolute top-0.5 h-3.5 w-3.5 rounded-pill bg-white shadow transition-transform ${enabled ? "translate-x-[14px]" : "translate-x-0.5"}`} /></button>;
}

function Rail() {
  const items = [{ label: "Overview", icon: Gauge }, { label: "Live Map", icon: MapIcon, active: true }, { label: "Forecast", icon: CloudRain }, { label: "Scenarios", icon: Wind }, { label: "Validation", icon: CircleHelp }, { label: "Sectors", icon: Waves }, { label: "Alerts", icon: Bell }];
  return <aside className="absolute bottom-3 left-3 top-3 z-30 flex w-[70px] flex-col items-center rounded-[17px] border border-slate-200/80 bg-white/90 py-4 shadow-[0_8px_28px_rgba(15,23,42,.12)] backdrop-blur-xl" aria-label="Map navigation"><div className="flex h-16 w-12 flex-col items-center justify-center text-center"><span className="text-[18px] font-bold tracking-tight text-slate-950">M<span className="text-primary">S</span></span><span className="mt-1 text-[7px] font-semibold uppercase tracking-[.16em] text-slate-500">Mausam</span></div><nav className="mt-5 flex flex-1 flex-col gap-2" aria-label="Workspace">{items.map(({ label, icon: Icon, active }) => <button key={label} type="button" aria-label={label} className={`relative flex h-11 w-12 items-center justify-center rounded-control transition-colors ${active ? "bg-primary-soft text-primary before:absolute before:left-[-9px] before:h-7 before:w-1 before:rounded-r-pill before:bg-primary" : "text-slate-500 hover:bg-slate-100 hover:text-slate-900"}`}><Icon className="h-[18px] w-[18px]" aria-hidden="true" /></button>)}</nav><div className="flex flex-col items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-pill bg-primary text-[10px] font-semibold text-white">BC</div><span className="[writing-mode:vertical-rl] text-[10px] font-semibold tracking-widest text-slate-400">मौसम सेतु</span></div></aside>;
}

function LayersPanel({ view }: { view: MapView }) {
  const [layers, setLayers] = useState(view.layers);
  return <section className="absolute left-[101px] top-[108px] z-20 w-[228px] rounded-panel border border-slate-200/80 bg-white/92 p-4 shadow-[0_8px_24px_rgba(15,23,42,.1)] backdrop-blur-xl" aria-label="Map layers"><div className="mb-3 flex items-center justify-between"><h2 className="text-[15px] font-semibold text-slate-950">Layers</h2><Settings2 className="h-4 w-4 text-slate-400" /></div><div className="space-y-0.5">{layers.map((layer) => <div key={layer.id} className={`flex min-h-[30px] items-center justify-between gap-3 rounded-control px-2 ${layer.selected ? "bg-sky-50" : ""}`}><span className={`text-[11px] ${layer.available ? "text-slate-700" : "text-slate-400"}`}>{layer.label}{!layer.available ? " · unavailable" : ""}</span><Toggle label={layer.label} enabled={layer.enabled} onChange={() => layer.available && setLayers((current) => current.map((item) => item.id === layer.id ? { ...item, enabled: !item.enabled } : item))} /></div>)}</div><div className="mt-4 border-t border-slate-200 pt-3"><div className="mb-2 flex items-center justify-between"><span className="text-[11px] text-slate-600">Overlay opacity</span><span className="font-mono text-[11px] text-slate-800">72%</span></div><input aria-label="Overlay opacity" type="range" min="0" max="100" defaultValue="72" className="h-1.5 w-full accent-primary" /></div></section>;
}

function BasinTabs() {
  const [active, setActive] = useState("Cauvery");
  return <div className="absolute right-5 top-[107px] z-20 flex h-[51px] items-center gap-1 rounded-panel border border-slate-200/80 bg-white/92 p-1.5 shadow-[0_8px_24px_rgba(15,23,42,.1)] backdrop-blur-xl">{["Cauvery", "Krishna", "Godavari", "Mahanadi", "All India"].map((name) => <button key={name} type="button" onClick={() => setActive(name)} className={`h-9 rounded-control px-3 text-[11px] transition-colors ${active === name ? "bg-primary text-white" : "text-slate-600 hover:bg-slate-100"}`}>{name}</button>)}<button type="button" aria-label="Search basins" className="ml-1 flex h-9 w-9 items-center justify-center rounded-control border-l border-slate-200 text-slate-500"><Search className="h-4 w-4" /></button></div>;
}

function MapBackground({ view }: { view: MapView }) {
  return <div className="absolute inset-0 overflow-hidden bg-[#dcecf5]"><StaticBasinMap values={view.rainfallGrid?.values ?? []} reservoirs={[]} showControls={false} className="h-full w-full bg-[#dcecf5] [&>img]:opacity-80" /><div className="pointer-events-none absolute inset-0 bg-[linear-gradient(115deg,rgba(255,255,255,.08),transparent_40%,rgba(7,91,180,.06))]" /><div className="pointer-events-none absolute left-[27%] top-[20%] h-40 w-52 rounded-[50%] border border-white/50 opacity-60" /><div className="pointer-events-none absolute left-[30%] top-[25%] h-48 w-72 rounded-[50%] border border-white/40 opacity-50" /><div className="pointer-events-none absolute left-[40%] top-[38%] h-16 w-16 rounded-[50%] border-2 border-primary/60 bg-primary/20 shadow-[0_0_0_10px_rgba(0,97,254,.12)]" aria-label="Selected grid cell" /><span className="absolute left-[40.3%] top-[35%] rounded bg-white/85 px-2 py-1 text-[11px] font-semibold text-slate-800">{view.selectedCell.place}</span><span className="absolute left-[29%] top-[32%] text-[11px] font-semibold tracking-[.18em] text-slate-500/80">KARNATAKA</span><span className="absolute left-[43%] top-[66%] text-[11px] font-semibold tracking-[.18em] text-slate-500/80">TAMIL NADU</span><span className="absolute left-[55%] top-[30%] text-[13px] italic text-sky-700/70">Bay of Bengal</span><span className="absolute left-[15%] top-[47%] text-[13px] italic text-sky-700/70">Arabian Sea</span></div>;
}

function NavigationControls() { return <div className="absolute bottom-[275px] left-[102px] z-10 flex flex-col overflow-hidden rounded-control border border-slate-200/90 bg-white/90 shadow-md backdrop-blur-xl">{[{ label: "Zoom in", icon: Plus }, { label: "Zoom out", icon: Minus }, { label: "Locate me", icon: LocateFixed }, { label: "Orient north", icon: Navigation }].map(({ label, icon: Icon }, index) => <button key={label} type="button" aria-label={label} className={`flex h-11 w-11 items-center justify-center text-slate-600 hover:text-primary ${index < 3 ? "border-b border-slate-200" : ""}`}><Icon className="h-4 w-4" /></button>)}</div>; }
function Legend() { return <div className="absolute bottom-[275px] left-[158px] z-10 w-[209px] rounded-control border border-slate-200/80 bg-white/88 p-3 shadow-md backdrop-blur-xl"><p className="text-[11px] font-semibold text-slate-800">Rainfall · mm/day</p><div className="mt-2 h-2 rounded-pill bg-gradient-to-r from-[#dceeff] via-[#74b5fb] to-[#0061fe]" /><div className="mt-1 flex justify-between font-mono text-[9px] text-slate-500"><span>0</span><span>25</span><span>50</span><span>75</span><span>100+</span></div></div>; }
function UnsupportedOverlay({ label }: { label: string }) { return <div className="absolute right-[9%] top-[21%] z-10 rounded-control border border-slate-200/80 bg-white/90 px-3 py-2 text-[10px] text-slate-500 shadow-md backdrop-blur-xl">{label} · Unavailable from API</div>; }

function Inspector({ view, forecast }: { view: MapView; forecast: { p10: Array<number | null>; p50: Array<number | null>; p90: Array<number | null>; dates: string[] } }) {
  const { selectedCell } = view;
  const values = selectedCell.timeseries?.rain_mm_per_day ?? [];
  const points = forecast.dates.map((date, index) => ({ date, p10: forecast.p10[index] ?? null, p50: forecast.p50[index] ?? null, p90: forecast.p90[index] ?? null }));
  const max = Math.max(1, ...points.map((point) => point.p90 ?? 0));
  return <aside className="absolute right-[7.2%] top-[306px] z-20 w-[350px] rounded-panel border border-slate-200/80 bg-white/95 p-5 shadow-[0_10px_30px_rgba(15,23,42,.14)] backdrop-blur-xl" aria-label="Selected grid cell inspector"><div className="flex items-start justify-between"><div><h2 className="text-[17px] font-semibold text-slate-950">{selectedCell.place}</h2><p className="mt-0.5 text-[11px] text-slate-500">{selectedCell.kind} · {selectedCell.lat_deg_north === null ? "Unavailable" : `${selectedCell.lat_deg_north.toFixed(2)} °N`}, {selectedCell.lon_deg_east === null ? "Unavailable" : `${selectedCell.lon_deg_east.toFixed(2)} °E`}</p></div><X className="h-4 w-4 text-slate-400" /></div><div className="mt-5"><p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-slate-500">Current analysis</p><div className="grid grid-cols-4 gap-2">{selectedCell.metrics.map((metric) => <div key={metric.label}><p className="text-[10px] text-slate-500">{metric.label}</p><p className={`mt-1 font-mono text-[14px] font-semibold ${metric.tone === "warning" ? "text-orange-500" : "text-primary"}`}>{display(metric.value)}</p><p className="text-[9px] text-slate-400">{metric.unit}</p></div>)}</div></div><div className="mt-5"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Forecast p10 / p50 / p90</p><span className="text-[10px] text-slate-400">mm/day</span></div><div className="mt-3 flex h-[96px] items-end justify-between gap-1">{points.length ? points.map((point) => <div key={point.date} className="flex h-full flex-1 flex-col items-center justify-end gap-1"><span className="font-mono text-[8px] text-slate-600">{display(point.p50)}</span><div className="w-full rounded-t-sm bg-primary-soft" style={{ height: `${Math.max(4, (point.p90 ?? 0) / max * 64)}px` }} /><span className="text-[8px] text-slate-400">{formatDate(point.date)}</span></div>) : <span className="text-[10px] text-slate-500">Forecast unavailable</span>}</div></div><div className="mt-4 rounded-control bg-slate-50 px-3 py-2"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Data status</p><p className="mt-1 text-[12px] font-semibold text-slate-600">{selectedCell.unavailableLabel ?? selectedCell.status}</p><p className="mt-1 text-[10px] text-slate-500">Latest timeseries value: {display(values.at(-1), "mm/day")}</p></div></aside>;
}

function Timeline({ view }: { view: MapView }) {
  const [playing, setPlaying] = useState(false); const [selected, setSelected] = useState(view.timeline.at(-1)?.date ?? ""); const selectedIndex = Math.max(0, view.timeline.findIndex((item) => item.date === selected));
  return <section className="absolute bottom-[35px] left-[8.3%] right-[19.5%] z-20 h-[198px] rounded-panel border border-slate-200/80 bg-white/94 px-5 py-4 shadow-[0_10px_30px_rgba(15,23,42,.13)] backdrop-blur-xl" aria-label="Map playback timeline"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><button type="button" aria-label={playing ? "Pause timeline" : "Play timeline"} onClick={() => setPlaying(!playing)} className="flex h-9 w-9 items-center justify-center rounded-pill border border-primary text-primary">{playing ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4 fill-current" />}</button><span className="ml-3 text-[16px] font-semibold tabular-nums text-slate-900">{formatIst(selected)}</span></div><div className="flex items-center gap-2"><button type="button" onClick={() => setSelected(view.timeline.at(-1)?.date ?? "")} className="h-9 rounded-control border border-primary bg-primary-soft px-3 text-[11px] font-semibold text-primary">Now</button><button type="button" aria-label="Open calendar" className="flex h-9 w-9 items-center justify-center rounded-control border border-cardBorder text-slate-500"><CalendarDays className="h-4 w-4" /></button></div></div><div className="relative mt-8 px-1"><div className="absolute left-0 right-0 top-3 h-px bg-slate-300" /><div className="absolute left-0 top-3 h-px bg-primary" style={{ width: `${view.timeline.length > 1 ? selectedIndex / (view.timeline.length - 1) * 100 : 0}%` }} /><div className="relative flex justify-between">{view.timeline.map((item) => <button key={item.date} type="button" onClick={() => setSelected(item.date)} aria-label={`${formatDate(item.date)}`} className="group flex w-7 flex-col items-center"><span className={`z-10 mt-0.5 h-5 w-5 rounded-pill border-2 ${item.date === selected ? "border-primary bg-white ring-4 ring-primary/15" : "border-primary bg-primary"}`} /><span className={`mt-3 whitespace-nowrap text-[9px] ${item.date === selected ? "font-semibold text-primary" : "text-slate-500"}`}>{formatDate(item.date)}</span></button>)}</div></div><div className="mt-6 flex items-center gap-5 text-[10px] text-slate-500"><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-pill bg-primary" />Observed</span><span className="ml-auto font-mono text-slate-400">{selected ? `${formatDate(selected)} selected` : "Unavailable"}</span></div></section>;
}

function StatusAndMetrics({ view }: { view: MapView }) {
  const assimilation = view.assimilation;
  const metrics = [{ label: "Rainfall", value: view.selectedCell.metrics[0]?.value, unit: "mm/day", series: view.selectedCell.timeseries?.rain_mm_per_day ?? [] }, { label: "Tmax", value: view.selectedCell.metrics[1]?.value, unit: "°C", series: view.selectedCell.timeseries?.tmax_c ?? [] }, { label: "Completeness", value: view.rainfallGrid?.completeness.completeness_pct ?? null, unit: "%", series: [] }];
  return <><div className="absolute bottom-[108px] right-[7.2%] z-20 flex w-[295px] items-center justify-between rounded-control border border-slate-200/80 bg-white/92 px-4 py-3 shadow-md backdrop-blur-xl"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-pill ${assimilation ? "bg-emerald-500" : "bg-slate-300"}`} /><div><p className="text-[11px] font-semibold text-slate-800">Assimilation</p><p className="text-[10px] text-slate-500">{assimilation ? `RMSE reduction ${assimilation.reduction_pct}%` : "Unavailable from API"}</p></div></div><span className="text-right text-[9px] text-slate-500">Cycle status<br /><span className="font-mono text-[11px] text-slate-700">{assimilation ? formatIst(assimilation.date_ist) : "Unavailable"}</span></span></div><div className="absolute bottom-[35px] right-[5.8%] z-20 flex h-[53px] w-[408px] divide-x divide-slate-200 overflow-hidden rounded-control border border-slate-200/80 bg-white/92 shadow-md">{metrics.map((metric) => <div key={metric.label} className="flex min-w-0 flex-1 items-center gap-2 px-3"><div className="min-w-0"><p className="truncate text-[9px] text-slate-500">{metric.label} ({metric.unit})</p><p className="font-mono text-[13px] font-semibold text-slate-900">{display(metric.value)}</p></div><MiniSparkline ariaLabel={`${metric.label} trend`} points={metric.series.filter((value): value is number => value !== null)} className="h-7 min-w-0 flex-1" /></div>)}</div><button type="button" aria-label="Fullscreen map" className="absolute bottom-[35px] right-[1.4%] z-20 flex h-[53px] w-[53px] items-center justify-center rounded-control border border-slate-200/80 bg-white/92 text-slate-600 shadow-md"><Expand className="h-4 w-4" /></button></>;
}

export default function MapPage() {
  const dates = useDates(); const selectedDate = dates.data?.dates.at(-1) ?? null; const grid = useGrid(selectedDate); const timeseries = useTimeseries(12.3, 76.6, 7, selectedDate ?? undefined); const assimilation = useAssimilation(selectedDate); const forecast = useForecast(selectedDate, 7);
  const view = useMemo(() => transformMap(grid.data, timeseries.data, assimilation.data, 12.3, 76.6), [grid.data, timeseries.data, assimilation.data]);
  const forecastValues = useMemo(() => ({ dates: forecast.data?.dates ?? [], p10: forecast.data ? forecastGridForSelectedCell(forecast.data.rain.p10, grid.data ?? null, view.selectedCell.lat_deg_north ?? 12.3, view.selectedCell.lon_deg_east ?? 76.6) : [], p50: forecast.data ? forecastGridForSelectedCell(forecast.data.rain.p50, grid.data ?? null, view.selectedCell.lat_deg_north ?? 12.3, view.selectedCell.lon_deg_east ?? 76.6) : [], p90: forecast.data ? forecastGridForSelectedCell(forecast.data.rain.p90, grid.data ?? null, view.selectedCell.lat_deg_north ?? 12.3, view.selectedCell.lon_deg_east ?? 76.6) : [] }), [forecast.data, grid.data, view.selectedCell.lat_deg_north, view.selectedCell.lon_deg_east]);
  const error = dates.error || grid.error || timeseries.error || assimilation.error || forecast.error; const retry = () => Promise.all([dates.mutate(), grid.mutate(), timeseries.mutate(), assimilation.mutate(), forecast.mutate()]);
  if (error) return <div className="p-6"><ErrorState title="Live map unavailable" description={String((error as Error).message ?? "The map data could not be loaded.")} onRetry={retry} /></div>;
  if (!dates.data || grid.isLoading) return <div className="p-6"><Skeleton variant="card" label="Loading live map" /></div>;
  return <div className="fixed inset-0 z-50 min-h-screen overflow-hidden bg-[#dcecf5] text-slate-900"><MapBackground view={view} /><Rail /><header className="absolute left-[99px] right-4 top-3 z-30 flex h-[75px] items-center justify-between rounded-panel border border-slate-200/80 bg-white/90 px-6 shadow-[0_8px_24px_rgba(15,23,42,.1)] backdrop-blur-xl"><div><div className="flex items-center gap-3"><h1 className="text-[20px] font-bold tracking-tight">Live Map</h1><span className="inline-flex items-center gap-1.5 text-[11px] text-emerald-600"><span className="h-2 w-2 rounded-pill bg-emerald-500" />Live</span></div><p className="mt-1 text-[12px] text-slate-500">Cauvery Basin · {formatIst(grid.data?.date_ist)}</p></div><div className="flex items-center gap-2"><button type="button" className="flex h-10 items-center gap-2 rounded-control border border-cardBorder bg-white/70 px-4 text-[11px] text-slate-600"><Download className="h-3.5 w-3.5" />Export</button><button type="button" className="flex h-10 items-center gap-2 rounded-control border border-cardBorder bg-white/70 px-4 text-[11px] text-slate-600"><Share2 className="h-3.5 w-3.5" />Share</button><button type="button" aria-label="Notifications" className="relative flex h-10 w-10 items-center justify-center rounded-control border border-cardBorder bg-white/70 text-slate-600"><Bell className="h-4 w-4" /></button><button type="button" className="flex h-10 items-center gap-2 rounded-control border border-cardBorder bg-white/70 px-2 text-[11px] font-semibold"><span className="flex h-7 w-7 items-center justify-center rounded-pill bg-primary text-[10px] text-white">BC</span><ChevronDown className="h-3.5 w-3.5 text-slate-400" /></button></div></header><LayersPanel view={view} /><BasinTabs /><NavigationControls /><Legend /><UnsupportedOverlay label="Storm and reservoir overlays" /><Inspector view={view} forecast={forecastValues} /><Timeline view={view} /><StatusAndMetrics view={view} /></div>;
}
