import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#F7F8FA",
        workspace: "rgba(249, 250, 250, 0.92)",
        card: {
          DEFAULT: "rgba(255, 255, 255, 0.88)",
          solid: "#FEFFFE",
          muted: "#F1F6FA",
          foreground: "#111318",
        },
        cardBorder: "#E1E4E8",
        divider: "#D8DCE2",
        textPrimary: "#111318",
        textSecondary: "#56606B",
        textTertiary: "#7A8390",
        textInverse: "#FFFFFF",
        primary: {
          DEFAULT: "#0061FE",
          strong: "#0854FE",
          soft: "#EAF2FE",
          foreground: "#FFFFFF",
        },
        positive: { DEFAULT: "#07945B", soft: "#E5FCED" },
        warning: { DEFAULT: "#F57602", soft: "#FEF7EA" },
        critical: {
          DEFAULT: "#ED3335",
          strong: "#EC3736",
          soft: "#FDEBEC",
        },
        rain: {
          0: "#DDEBFF",
          25: "#ABD2FF",
          50: "#8FBEFD",
          75: "#3D91FB",
          100: "#0061FE",
        },
        temperature: { low: "#FEF3C7", high: "#B91C1C" },
        anomaly: {
          negative: "#E56604",
          neutral: "#FFFFFF",
          positive: "#143CB9",
        },
        missing: "#E5E7EB",
        foreground: "#111318",
        popover: { DEFAULT: "#FEFFFE", foreground: "#111318" },
        secondary: { DEFAULT: "#F1F6FA", foreground: "#111318" },
        muted: { DEFAULT: "#F1F6FA", foreground: "#56606B" },
        accent: { DEFAULT: "#EAF2FE", foreground: "#111318" },
        destructive: { DEFAULT: "#ED3335", foreground: "#FFFFFF" },
        border: "#E1E4E8",
        input: "#E1E4E8",
        ring: "#0061FE",
      },
      borderRadius: {
        card: "12px",
        panel: "16px",
        shell: "20px",
        control: "8px",
        button: "8px",
        pill: "9999px",
        lg: "12px",
        md: "8px",
        sm: "8px",
      },
      spacing: {
        card: "16px",
        "card-lg": "20px",
        "row-gap": "12px",
        "column-gap": "12px",
        workspace: "16px",
        sidebar: "240px",
        topbar: "72px",
        cycle: "48px",
        control: "40px",
        target: "44px",
        "desktop-min": "1180px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Arial", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        hero: ["48px", { lineHeight: "1", fontWeight: "600" }],
        page: ["24px", { lineHeight: "1.2", fontWeight: "650" }],
        title: ["16px", { lineHeight: "1.3", fontWeight: "600" }],
        label: ["13px", { lineHeight: "1.35", fontWeight: "600" }],
        body: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["11px", { lineHeight: "1.4", fontWeight: "500" }],
        eyebrow: [
          "11px",
          { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.06em" },
        ],
      },
      boxShadow: {
        "elevation-card": "0 8px 24px rgba(20, 30, 45, 0.08)",
        "elevation-floating": "0 12px 32px rgba(20, 30, 45, 0.12)",
      },
      backdropBlur: { card: "12px", shell: "16px" },
      transitionDuration: { fast: "150ms", page: "200ms", map: "300ms" },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
